services:

  proyecto-ciberseguridad:
    build: .
    container_name: proyecto-ciberseguridad
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql://soc_ai_app:${DB_PASSWORD:-soc_ai_app}@db:5432/soc_ai_db
      SECRET_KEY: ${SECRET_KEY:-cambia-esto-por-una-clave-aleatoria-larga}
    depends_on:
      - ollama
      - db
    restart: unless-stopped

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    container_name: soc-ai-db
    environment:
      POSTGRES_DB: soc_ai_db
      POSTGRES_USER: soc_ai_app
      POSTGRES_PASSWORD: ${DB_PASSWORD:-soc_ai_app}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  ollama_data:
  postgres_data: